profile: "dev"
message: "configurations in ${profile}"

#####################################
# HTTP Configuration
#####################################
https:
  host: "localhost"
  port: "8082"
http:
  host: "localhost"
  port: "8081"
  
#####################################
# Certifications
#####################################
tls:
  keystore:
    basePath: "certificates/${profile}/keystore.jks"
  truststore:
    basePath: "certificates/${profile}/truststore.ts"