profile: "TST"
message: "configurations in ${profile}"

#####################################
# HTTP Configuration
#####################################
https:
  host: "localhost"
  port: "8082"
http:
  host: "localhost"
  port: "8081"
  
#####################################
# Certifications
#####################################
tls:
  keystore:
    basePath: "certificates/${profile}/keystore.jks"
    password: "password"
  truststore:
    basePath: "certificates/${profile}/truststore.ts"
    password: "![Qvg+/L86Aw7HxUc+4uszNw==]"